version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: trinhna
      MONGO_INITDB_ROOT_PASSWORD: anhtrinh05102003
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
